// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using SMARsvp.Infrastructure.Data;

#nullable disable

namespace SMARsvp.Infrastructure.Migrations
{
    [DbContext(typeof(SMARsvpDbContext))]
    [Migration("20260919023019_InitialLayoutMigration")]
    partial class InitialLayoutMigration
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.12")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("SMARsvp.Domain.Entities.LayoutCliente", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<decimal>("AlturaPaginaMm")
                        .HasPrecision(10, 2)
                        .HasColumnType("decimal(10,2)");

                    b.Property<string>("Cliente")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<int>("FormatoPapel")
                        .HasColumnType("int");

                    b.Property<decimal>("LarguraPaginaMm")
                        .HasPrecision(10, 2)
                        .HasColumnType("decimal(10,2)");

                    b.Property<string>("NomeArquivoModelo")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NomeModelo")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<int>("Orientacao")
                        .HasColumnType("int");

                    b.Property<int>("QuantidadePaginasPadrao")
                        .HasColumnType("int");

                    b.Property<int>("Versao")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Layouts");
                });

            modelBuilder.Entity("SMARsvp.Domain.Entities.PaginaModeloImagem", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("ImagemBase64")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("LayoutClienteId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("NumeroPagina")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("LayoutClienteId");

                    b.ToTable("PaginasModelo");
                });

            modelBuilder.Entity("SMARsvp.Domain.Entities.QueryValidacao", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("LayoutClienteId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Sql")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("LayoutClienteId");

                    b.ToTable("QueriesValidacao");
                });

            modelBuilder.Entity("SMARsvp.Domain.Entities.RegiaoCampo", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<decimal>("AlturaMm")
                        .HasPrecision(10, 2)
                        .HasColumnType("decimal(10,2)");

                    b.Property<bool>("EhIdentificadorPrimeiraPagina")
                        .HasColumnType("bit");

                    b.Property<decimal>("LarguraMm")
                        .HasPrecision(10, 2)
                        .HasColumnType("decimal(10,2)");

                    b.Property<Guid>("LayoutClienteId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("NomeCampo")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int>("Pagina")
                        .HasColumnType("int");

                    b.Property<string>("TextoEsperadoIdentificador")
                        .HasMaxLength(250)
                        .HasColumnType("nvarchar(250)");

                    b.Property<decimal>("XMm")
                        .HasPrecision(10, 2)
                        .HasColumnType("decimal(10,2)");

                    b.Property<decimal>("YMm")
                        .HasPrecision(10, 2)
                        .HasColumnType("decimal(10,2)");

                    b.HasKey("Id");

                    b.HasIndex("LayoutClienteId");

                    b.ToTable("RegioesCampos");
                });

            modelBuilder.Entity("SMARsvp.Domain.Entities.RegraValidacao", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("CampoCarne")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("CampoRetornado")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Operador")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<Guid>("QueryValidacaoId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("QueryValidacaoId");

                    b.ToTable("RegrasValidacao");
                });

            modelBuilder.Entity("SMARsvp.Domain.Entities.PaginaModeloImagem", b =>
                {
                    b.HasOne("SMARsvp.Domain.Entities.LayoutCliente", "LayoutCliente")
                        .WithMany("PaginasModelo")
                        .HasForeignKey("LayoutClienteId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("LayoutCliente");
                });

            modelBuilder.Entity("SMARsvp.Domain.Entities.QueryValidacao", b =>
                {
                    b.HasOne("SMARsvp.Domain.Entities.LayoutCliente", "LayoutCliente")
                        .WithMany("QueriesValidacao")
                        .HasForeignKey("LayoutClienteId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("LayoutCliente");
                });

            modelBuilder.Entity("SMARsvp.Domain.Entities.RegiaoCampo", b =>
                {
                    b.HasOne("SMARsvp.Domain.Entities.LayoutCliente", "LayoutCliente")
                        .WithMany("Campos")
                        .HasForeignKey("LayoutClienteId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("LayoutCliente");
                });

            modelBuilder.Entity("SMARsvp.Domain.Entities.RegraValidacao", b =>
                {
                    b.HasOne("SMARsvp.Domain.Entities.QueryValidacao", "QueryValidacao")
                        .WithMany("Regras")
                        .HasForeignKey("QueryValidacaoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("QueryValidacao");
                });

            modelBuilder.Entity("SMARsvp.Domain.Entities.LayoutCliente", b =>
                {
                    b.Navigation("Campos");

                    b.Navigation("PaginasModelo");

                    b.Navigation("QueriesValidacao");
                });

            modelBuilder.Entity("SMARsvp.Domain.Entities.QueryValidacao", b =>
                {
                    b.Navigation("Regras");
                });
#pragma warning restore 612, 618
        }
    }
}
