// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using SMARsvp.Infrastructure.Data;

#nullable disable

namespace SMARsvp.Infrastructure.Migrations
{
    [DbContext(typeof(SMARsvpDbContext))]
    [Migration("20260923230804_RemoverTabelaConexaoBanco")]
    partial class RemoverTabelaConexaoBanco
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.12");

            modelBuilder.Entity("SMARsvp.Domain.Entities.LayoutCliente", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<decimal>("AlturaPaginaMm")
                        .HasPrecision(10, 2)
                        .HasColumnType("TEXT");

                    b.Property<string>("Cliente")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("TEXT");

                    b.Property<decimal>("LarguraPaginaMm")
                        .HasPrecision(10, 2)
                        .HasColumnType("TEXT");

                    b.Property<string>("NomeArquivoModelo")
                        .HasColumnType("TEXT");

                    b.Property<string>("NomeModelo")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("TEXT");

                    b.Property<int>("Versao")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.ToTable("Layouts");
                });

            modelBuilder.Entity("SMARsvp.Domain.Entities.LogSistema", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("DataHora")
                        .HasColumnType("TEXT");

                    b.Property<string>("Detalhes")
                        .HasColumnType("TEXT");

                    b.Property<string>("Mensagem")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Origem")
                        .IsRequired()
                        .HasMaxLength(250)
                        .HasColumnType("TEXT");

                    b.Property<string>("StackTrace")
                        .HasColumnType("TEXT");

                    b.Property<string>("Tipo")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("DataHora");

                    b.HasIndex("Tipo");

                    b.ToTable("Logs");
                });

            modelBuilder.Entity("SMARsvp.Domain.Entities.PaginaModeloImagem", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("ImagemBase64")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<Guid>("LayoutClienteId")
                        .HasColumnType("TEXT");

                    b.Property<int>("NumeroPagina")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("LayoutClienteId");

                    b.ToTable("PaginasModelo");
                });

            modelBuilder.Entity("SMARsvp.Domain.Entities.QueryValidacao", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<Guid>("LayoutClienteId")
                        .HasColumnType("TEXT");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("Sql")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("LayoutClienteId");

                    b.ToTable("QueriesValidacao");
                });

            modelBuilder.Entity("SMARsvp.Domain.Entities.RegiaoCampo", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<decimal>("AlturaMm")
                        .HasPrecision(10, 2)
                        .HasColumnType("TEXT");

                    b.Property<string>("ConsultaSql")
                        .HasColumnType("TEXT");

                    b.Property<string>("IdentificadorAnterior")
                        .HasMaxLength(150)
                        .HasColumnType("TEXT");

                    b.Property<string>("IdentificadorPagina")
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<decimal>("LarguraMm")
                        .HasPrecision(10, 2)
                        .HasColumnType("TEXT");

                    b.Property<Guid>("LayoutClienteId")
                        .HasColumnType("TEXT");

                    b.Property<string>("NomeCampo")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<int>("Pagina")
                        .HasColumnType("INTEGER");

                    b.Property<string>("TextoEsperadoDocumento")
                        .HasMaxLength(250)
                        .HasColumnType("TEXT");

                    b.Property<string>("TextoEsperadoPagina")
                        .HasMaxLength(250)
                        .HasColumnType("TEXT");

                    b.Property<int>("TipoClassificacao")
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("XMm")
                        .HasPrecision(10, 2)
                        .HasColumnType("TEXT");

                    b.Property<decimal>("YMm")
                        .HasPrecision(10, 2)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("LayoutClienteId");

                    b.ToTable("RegioesCampos");
                });

            modelBuilder.Entity("SMARsvp.Domain.Entities.RegraValidacao", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("CampoCarne")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("CampoRetornado")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("Operador")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("TEXT");

                    b.Property<Guid>("QueryValidacaoId")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("QueryValidacaoId", "CampoRetornado", "Operador", "CampoCarne")
                        .IsUnique();

                    b.ToTable("RegrasValidacao");
                });

            modelBuilder.Entity("SMARsvp.Domain.Entities.PaginaModeloImagem", b =>
                {
                    b.HasOne("SMARsvp.Domain.Entities.LayoutCliente", "LayoutCliente")
                        .WithMany("PaginasModelo")
                        .HasForeignKey("LayoutClienteId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("LayoutCliente");
                });

            modelBuilder.Entity("SMARsvp.Domain.Entities.QueryValidacao", b =>
                {
                    b.HasOne("SMARsvp.Domain.Entities.LayoutCliente", "LayoutCliente")
                        .WithMany("QueriesValidacao")
                        .HasForeignKey("LayoutClienteId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("LayoutCliente");
                });

            modelBuilder.Entity("SMARsvp.Domain.Entities.RegiaoCampo", b =>
                {
                    b.HasOne("SMARsvp.Domain.Entities.LayoutCliente", "LayoutCliente")
                        .WithMany("Campos")
                        .HasForeignKey("LayoutClienteId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("LayoutCliente");
                });

            modelBuilder.Entity("SMARsvp.Domain.Entities.RegraValidacao", b =>
                {
                    b.HasOne("SMARsvp.Domain.Entities.QueryValidacao", "QueryValidacao")
                        .WithMany("Regras")
                        .HasForeignKey("QueryValidacaoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("QueryValidacao");
                });

            modelBuilder.Entity("SMARsvp.Domain.Entities.LayoutCliente", b =>
                {
                    b.Navigation("Campos");

                    b.Navigation("PaginasModelo");

                    b.Navigation("QueriesValidacao");
                });

            modelBuilder.Entity("SMARsvp.Domain.Entities.QueryValidacao", b =>
                {
                    b.Navigation("Regras");
                });
#pragma warning restore 612, 618
        }
    }
}
